### PR TITLE
Fix #6 ("Cannot serialize a null itemstack")

### LINKED ISSUE #6: InvalidArgumentException: "Cannot serialize a null itemstack"
```
2023-07-14 [18:24:22.891] [Server thread/CRITICAL]: InvalidArgumentException: "Cannot serialize a null itemstack" (EXCEPTION) in "pmsrc/src/data/bedrock/item/ItemSerializer" at line 94
--- Stack trace ---
  #0 pmsrc/src/data/bedrock/item/ItemSerializer(134): pocketmine\data\bedrock\item\ItemSerializer->serializeType(object pocketmine\item\ItemBlock#122768)
  #1 pmsrc/src/item/Item(707): pocketmine\data\bedrock\item\ItemSerializer->serializeStack(object pocketmine\item\ItemBlock#122768, null)
  #2 plugins/PMArmorStand.phar/src/muqsit/pmarmorstand/entity/ArmorStandEntity(136): pocketmine\item\Item->nbtSerialize()
  #3 pmsrc/src/world/World(2866): muqsit\pmarmorstand\entity\ArmorStandEntity->saveNBT()
  ....
```
I suppose this may be caused by an armor stand trying to encode an empty slot?

### PR DESCRIPTION
**Pull request by Wertzui123**

### CODE REVIEW

File: src/muqsit/pmarmorstand/entity/ArmorStandEntity.php [hunk 1]
```diff
@@ -128,12 +128,16 @@ public function saveNBT() : CompoundTag{
 		$nbt = parent::saveNBT();
 
 		$armor_pieces = [];
-		foreach($this->getArmorInventory()->getContents() as $slot => $item){
-			$armor_pieces[] = $item->nbtSerialize($slot);
+		foreach($this->getArmorInventory()->getContents() as $slot => $item) {
+			if (!$item->isNull()) {
```
Comment (Muqsit) [inline src/muqsit/pmarmorstand/entity/ArmorStandEntity.php]: This check isn't needed because `Inventory::getContents()` (unlike `Inventory::getContents(true)`) always returns non-null items

File: src/muqsit/pmarmorstand/entity/ArmorStandEntity.php [hunk 2]
```diff
@@ -128,12 +128,16 @@ public function saveNBT() : CompoundTag{
...
+				$armor_pieces[] = $item->nbtSerialize($slot);
+			}
 		}
 		$nbt->setTag(self::TAG_ARMOR_INVENTORY, new ListTag($armor_pieces, NBT::TAG_Compound));
 
-		$nbt->setTag(self::TAG_HELD_ITEM, $this->item_in_hand->nbtSerialize());
+		if (!$this->item_in_hand->isNull()) {
```
Comment (Muqsit) [inline src/muqsit/pmarmorstand/entity/ArmorStandEntity.php]: Formatting correction: if statement shouldn't have surrounding spaces (its the same formatting that PocketMine uses)

**Review by Muqsit — CHANGES_REQUESTED** [review]

File: src/muqsit/pmarmorstand/entity/ArmorStandEntity.php [hunk 3]
```diff
@@ -128,12 +128,14 @@ public function saveNBT() : CompoundTag{
 		$nbt = parent::saveNBT();
 
 		$armor_pieces = [];
-		foreach($this->getArmorInventory()->getContents() as $slot => $item){
+		foreach($this->getArmorInventory()->getContents() as $slot => $item) {
```
Comment (Muqsit) [inline src/muqsit/pmarmorstand/entity/ArmorStandEntity.php]: Formatting needs correction here as well 😛

**Review by Muqsit — CHANGES_REQUESTED** [review]

**Review by Muqsit — APPROVED** [review]
